//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTES
    {
        public int NOTID { get; set; }
        public Nullable<int> STUDENT { get; set; }
        public Nullable<int> LESSON { get; set; }
        public Nullable<short> TEST1 { get; set; }
        public Nullable<short> TEST2 { get; set; }
        public Nullable<short> TEST3 { get; set; }
        public Nullable<decimal> AVERAGE { get; set; }
        public Nullable<bool> RESULT { get; set; }
    
        public virtual TBLLESSON TBLLESSON { get; set; }
        public virtual TBLSTUDENT TBLSTUDENT { get; set; }
    }
}
